/* ============================================
   VIBECRAFT — Generator Engine
   The core that composes all pieces into a 
   complete system instructions file.
   ============================================ */

import type { GeneratorConfig, GeneratedOutput, VibeDefinition, UserTier } from "@/lib/types";
import { getVibeById } from "./vibes";
import { getStackById } from "./stacks";
import { getRuleById } from "./templates/rules";
import { getIDETarget } from "./formatters/ide-targets";

interface GenerateOptions {
  config: GeneratorConfig;
  userTier: UserTier;
}

export function generateSystemInstructions({
  config,
  userTier,
}: GenerateOptions): GeneratedOutput[] {
  const vibe = getVibeById(config.vibe);
  if (!vibe) throw new Error(`Vibe not found: ${config.vibe}`);

  // Check tier access
  if (vibe.tier !== "free" && (userTier === "free")) {
    throw new Error(`Vibe "${vibe.name}" requires a Pro plan or higher`);
  }

  const outputs: GeneratedOutput[] = [];

  for (const ideId of config.targetIdes) {
    const ide = getIDETarget(ideId);
    if (!ide) continue;

    const content = composeContent(vibe, config, userTier, ide.name);
    outputs.push({
      content,
      fileName: ide.fileName,
      ideName: ide.name,
      iconName: ide.iconName,
    });
  }

  return outputs;
}

function composeContent(
  vibe: VibeDefinition,
  config: GeneratorConfig,
  userTier: UserTier,
  ideName: string
): string {
  const sections: string[] = [];
  const isFree = userTier === "free";

  // --- Header ---
  sections.push(buildHeader(vibe, ideName, isFree));

  // --- Technology Rules ---
  sections.push(buildTechnologySection(config));

  // --- Design Vibe ---
  sections.push(buildDesignVibeSection(vibe));

  // --- Component Patterns ---
  sections.push(buildComponentPatternsSection(vibe));

  // --- Animation Rules ---
  if (config.stacks.animation && vibe.animationRules && vibe.animationRules.length > 0) {
    sections.push(buildAnimationSection(vibe));
  }

  // --- AI Rules ---
  sections.push(buildAIRulesSection(config, userTier));

  // --- Special Instructions ---
  sections.push(buildSpecialInstructionsSection(vibe));

  // --- Enterprise Blueprints ---
  sections.push(buildEnterpriseSection(vibe));

  // --- Footer ---
  sections.push(buildFooter(isFree));

  return sections.filter(Boolean).join("\n\n");
}

// ---- Section Builders ----

function buildHeader(vibe: VibeDefinition, ideName: string, isFree: boolean): string {
  const lines = [
    `# VibeCraft Design System: ${vibe.name}`,
    `# Generated by VibeCraft (https://vibecraft.dev) — by changeshott`,
    `# Target: ${ideName}`,
    `# Generated: ${new Date().toISOString().split("T")[0]}`,
  ];

  if (isFree) {
    lines.push(
      `#`,
      `# ====================================================================`,
      `# ⚠️ GENERATED BY VIBECRAFT (FREE VERSION)`,
      `# Upgrade to Pro at https://vibecraft.dev/pricing to remove this watermark,`,
      `# unlock all premium vibes, and export to multiple IDEs simultaneously.`,
      `# ====================================================================`,
      `#`
    );
  } else {
    lines.push(`#`);
  }

  lines.push(`# ${vibe.description}`);
  lines.push("");
  lines.push("---");

  return lines.join("\n");
}

function buildTechnologySection(config: GeneratorConfig): string {
  const lines = ["## TECHNOLOGY RULES (Strict)", ""];

  const stackEntries = Object.entries(config.stacks);
  const allImports = new Set<string>();
  const allFileStructure = new Set<string>();

  for (const [, stackId] of stackEntries) {
    if (!stackId) continue;
    const stack = getStackById(stackId);
    if (!stack) continue;

    lines.push(`### ${stack.name} (v${stack.version})`);
    for (const rule of stack.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");

    if (stack.imports && stack.imports.length > 0) {
      stack.imports.forEach((i: string) => allImports.add(i));
    }
    if (stack.fileStructure && stack.fileStructure.length > 0) {
      stack.fileStructure.forEach((f: string) => allFileStructure.add(f));
    }
  }

  if (allImports.size > 0) {
    lines.push("### Allowed Core Imports");
    lines.push("```typescript");
    Array.from(allImports).forEach(i => lines.push(`import { ... } from "${i}";`));
    lines.push("```");
    lines.push("");
  }

  if (allFileStructure.size > 0) {
    lines.push("### Required File Structure");
    Array.from(allFileStructure).forEach(f => lines.push(`- \`${f}\``));
    lines.push("");
  }

  return lines.join("\n");
}

function buildDesignVibeSection(vibe: VibeDefinition): string {
  const lines = [
    `## DESIGN VIBE: ${vibe.name}`,
    "",
    `> ${vibe.description}`,
    "",
    "### Color Palette",
    "Use ONLY these colors. Do NOT invent new colors or use arbitrary values.",
    "",
  ];

  const colorEntries = Object.entries(vibe.colors) as [string, string][];
  for (const [name, value] of colorEntries) {
    const label = name.replace(/([A-Z])/g, " $1").trim();
    lines.push(`- **${label}**: \`${value}\``);
  }

  lines.push("");
  lines.push("### Typography");

  const typoEntries = Object.entries(vibe.typography) as [string, string][];
  for (const [name, value] of typoEntries) {
    const label = name.replace(/([A-Z])/g, " $1").trim();
    lines.push(`- **${label}**: \`${value}\``);
  }

  return lines.join("\n");
}

function buildComponentPatternsSection(vibe: VibeDefinition): string {
  const lines = [
    "## COMPONENT PATTERNS",
    "",
    "Use these exact class combinations for consistency. Customize content, NOT structure.",
    "",
  ];

  for (const pattern of vibe.componentPatterns) {
    lines.push(`### ${pattern.name}`);
    lines.push(`${pattern.description}`);
    lines.push("```");
    lines.push(pattern.classes);
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}

function buildAnimationSection(vibe: VibeDefinition): string {
  const lines = [
    "## ANIMATION RULES",
    "",
  ];

  for (const rule of vibe.animationRules) {
    lines.push(`- ${rule}`);
  }

  return lines.join("\n");
}

function buildAIRulesSection(config: GeneratorConfig, userTier: UserTier): string {
  const validRules = config.rules
    .map(id => getRuleById(id))
    .filter(rule => rule !== undefined && (rule.tier === "free" || userTier !== "free"));

  if (validRules.length === 0) {
    return "";
  }

  const lines = [
    "## AI BEHAVIOR RULES",
    "",
  ];

  for (const rule of validRules) {
    if (!rule) continue;
    lines.push(`### ${rule.name}`);
    lines.push(`${rule.description}`);
    lines.push("");
    for (const r of rule.rules) {
      lines.push(`- ${r}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function buildSpecialInstructionsSection(vibe: VibeDefinition): string {
  const lines = [
    "## SPECIAL INSTRUCTIONS FOR THIS VIBE",
    "",
  ];

  for (const instruction of vibe.specialInstructions) {
    lines.push(`- ${instruction}`);
  }

  return lines.join("\n");
}

function buildEnterpriseSection(vibe: VibeDefinition): string {
  if (!vibe.architectureNotes && (!vibe.enterpriseBlueprints || vibe.enterpriseBlueprints.length === 0)) {
    return "";
  }

  const lines = [
    "## ENTERPRISE ARCHITECTURE & BLUEPRINTS",
    "",
    "> *Note: These blueprints provide the structural foundation for this vibe.*",
    "",
  ];

  if (vibe.architectureNotes) {
    lines.push("### Architecture Notes");
    lines.push(vibe.architectureNotes);
    lines.push("");
  }

  if (vibe.enterpriseBlueprints && vibe.enterpriseBlueprints.length > 0) {
    lines.push("### Component & System Blueprints");
    lines.push("");

    for (const bp of vibe.enterpriseBlueprints) {
      lines.push(`#### ${bp.title}`);
      if (bp.description) {
        lines.push(bp.description);
      }
      lines.push("");
      lines.push(`\`\`\`${bp.language}`);
      lines.push(bp.code);
      lines.push(`\`\`\``);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function buildFooter(isFree: boolean): string {
  const lines = [
    "---",
    "",
    "## Summary",
    "",
    "Follow ALL rules above strictly. When in doubt, refer back to the design vibe section",
    "for colors, typography, and component patterns. Consistency is more important than creativity",
    "— every page and component should feel like part of the same application.",
  ];

  if (isFree) {
    lines.push("");
    lines.push("---");
    lines.push("*Generated with VibeCraft Free — Upgrade at https://vibecraft.dev/pricing*");
  }

  return lines.join("\n");
}
