import type { PricingPlan } from "@/lib/types";

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    period: "one-time",
    description: "Try VibeCraftz with basic vibes and limited options.",
    features: [
      "3 basic design vibes",
      "Next.js + Tailwind stack only",
      "1 IDE format (Cursor)",
      "Basic AI rules",
      "Watermark in output",
    ],
    highlighted: false,
    tier: "free",
  },
  {
    id: "starter",
    name: "Starter",
    price: 19,
    period: "one-time",
    description: "Unlock 1 premium vibe pack with full stack options.",
    features: [
      "1 premium vibe pack of your choice",
      "All tech stack options",
      "All IDE formats",
      "All AI rules",
      "No watermark",
    ],
    highlighted: false,
    tier: "starter",
  },
  {
    id: "pro",
    name: "Pro",
    price: 39,
    period: "one-time",
    description: "Full access to all vibes and the complete generator.",
    features: [
      "All design vibes (current + 1 year updates)",
      "All tech stack options",
      "All IDE formats",
      "All AI rules",
      "No watermark",
      "Priority email support",
    ],
    highlighted: true,
    tier: "pro",
  },
  {
    id: "pro-plus",
    name: "Pro+",
    price: 9,
    period: "monthly",
    description: "Everything in Pro, plus monthly new vibes and community.",
    features: [
      "Everything in Pro",
      "Monthly new vibe packs",
      "Early access to new features",
      "Community Discord access",
      "Vote on next vibes",
    ],
    highlighted: false,
    tier: "pro_plus",
  },
];
